CREATE TABLE esteems
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    liker_id   BIGINT  NOT NULL,
    liked_id   BIGINT  NOT NULL,
    esteem     BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT unique_like UNIQUE (liker_id, liked_id)
);

CREATE TABLE matches
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id   BIGINT,
    user2_id   BIGINT,
    created_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT unique_match UNIQUE (user1_id, user2_id)
)